services:
  http-server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    container_name: http-server
    ports:
      - "8080:8080"
    networks:
      - network-lab
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

  http-client:
    build:
      context: .
      dockerfile: ./Dockerfile.client
    container_name: http-client
    depends_on:
      http-server:
        condition: service_healthy
    networks:
      - network-lab
    command: ["python", "client.py", "http-server", "8080", "pdf1.pdf"]

networks:
  network-lab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16